"""Task 6, step 3 of 3: write the dataset summary used as Task 6 evidence.

Reads:
    data/users.csv, data/accounts.csv, data/score_history.csv   Output of steps 1 and 2.
Writes:
    docs/evidence/week-1/task-06-dataset-summary.md   One table row per user: scenario, cards, other
        accounts, card utilization (in INR, Indian digit grouping), score at the start and end of the
        period, and the latest factor change. Also printed to the terminal.

Run (after step 2):
    uv run python scripts/synthetic/step3_summary.py
"""

import pandas as pd

from creditcoach import config

DATA = config.ROOT / "data"
EVIDENCE = config.ROOT / "docs" / "evidence" / "week-1" / "task-06-dataset-summary.md"


def inr(amount: float) -> str:
    """Format a rupee amount with Indian digit grouping (lakh, crore).

    Example: 123456 -> "₹1,23,456"; 200000 -> "₹2,00,000".
    """
    digits = str(int(round(amount)))
    head, tail = digits[:-3], digits[-3:]
    groups = []
    while len(head) > 2:
        groups.insert(0, head[-2:])
        head = head[:-2]
    return "₹" + ",".join(([head] if head else []) + groups + [tail])


def main() -> None:
    """Read the dataset, build the summary table, and write it to the Task 6 evidence file."""
    import sys

    sys.path.insert(0, str(config.ROOT / "scripts" / "synthetic"))
    from step2_accounts_scores import SCENARIOS

    users = pd.read_csv(DATA / "users.csv", dtype=str, keep_default_na=False)
    accounts = pd.read_csv(DATA / "accounts.csv", keep_default_na=False)
    scores = pd.read_csv(DATA / "score_history.csv")

    with_history = scores.user_id.nunique()
    lines = [
        "# Task 6 Evidence: Synthetic Dataset Summary\n",
        "*Generated by `scripts/synthetic/step1_profiles.py`, `step2_accounts_scores.py` and `step3_summary.py`. "
        "Files: `data/users.csv`, `data/accounts.csv`, `data/score_history.csv`.*\n",
        "*Indian consumer context: amounts in ₹, scores on the 300–900 range used by Indian credit bureaus.*\n",
        f"**{len(users)} user profiles** (USR-001 from requirements.md + 12 from user interviews) · "
        f"**{len(accounts)} accounts** · **{len(scores)} monthly score records** · "
        f"**{with_history} users with 12 months of history (Oct 2025 to Sep 2026)**, "
        f"{len(users) - with_history} with no credit file\n",
        "| User | Name | Source | Scenario | Cards | Other accounts | Revolving utilization | Score Oct 2025 → Sep 2026 | Latest factor change |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for u in users.itertuples():
        acc = accounts[accounts.user_id == u.user_id]
        g = scores[scores.user_id == u.user_id]
        rev = acc[acc.credit_limit_inr != ""]
        cards = len(rev)
        other = ", ".join(acc[acc.credit_limit_inr == ""].account_type) or "none"
        if cards:
            bal, lim = rev.balance_inr.sum(), rev.credit_limit_inr.astype(float).sum()
            util = f"{inr(bal)} / {inr(lim)} = {bal / lim:.1%}"
        else:
            util = "n/a (no cards)"
        story = f"{g.score.iloc[0]} → {g.score.iloc[-1]}" if len(g) else "no credit file"
        scenario = "Utilization spike + hard inquiry" if u.user_id == "USR-001" else SCENARIOS.get(u.user_id, "Steady improver")
        source = "Persona" if u.user_id == "USR-001" else u.source.replace("Interview ", "")
        latest = g.primary_factor_change.iloc[-1] if len(g) else "—"
        lines.append(f"| {u.user_id} | {u.first_name} | {source} | {scenario} | {cards} | {other} | {util} | {story} | {latest} |")
    lines += [
        "",
        "**Validation (run on every generation):** accounts and scores reference existing users; card counts match "
        "each interview answer; scores stay within 300–900; every monthly change falls within its factor's range; "
        "any user above 30% utilization has a utilization change in the last 3 months; utilization ratios equal "
        "balance ÷ limit; USR-001's scores and utilization ratios are identical to `sample_data` (amounts scaled ×50 into ₹). **Result: all checks passed.**",
    ]
    EVIDENCE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
