"""Task 7: validate the RAG corpus and write the evidence summary (document count + sample-query coverage).

    uv run python scripts/task07_corpus_report.py
"""

import re
import sys

from creditcoach import config
from creditcoach.rag.corpus import parse_front_matter

CORPUS = config.ROOT / "corpus"
EVIDENCE = config.ROOT / "docs" / "evidence" / "week-1" / "task-07-corpus-summary.md"
REQUIRED = ["id", "title", "category", "source", "queries"]
CATEGORIES = {"scoring_factor": "Credit-scoring factors", "financial_literacy": "Financial literacy",
              "product_risk": "Product risk"}

SAMPLE_QUERIES = {
    1: "Why did my credit score drop 20 points this month?",
    2: "What's my current credit utilization ratio?",
    3: "I want to buy a car in 12 months — what should I focus on?",
    4: "Should I take out this payday loan to pay off my credit card?",
    5: "Remember that I'm saving for a car and want to hit a 720 score by next year.",
    6: "Can you guarantee my score will hit 720 if I do what you said?",
}
# Facts each query's answer depends on; every phrase must appear in at least one document tagged for that query.
KEY_FACTS = {
    1: ["utilization spike", "hard inquiry", "10 to 40 points", "2 to 10 points"],
    2: ["balance divided by your limit", "30%"],
    3: ["car loan", "hard inquiry", "utilization"],
    4: ["payday", "instant loan app", "don't report to the credit bureaus", "safer"],
    5: ["target score", "target date", "purpose"],
    6: ["guarantee", "not public"],
}
# Every section of credit_score_factors_guide.pdf must be represented.
GUIDE_SECTIONS = {"§1": "Payment history", "§2": "Credit utilization", "§3": "Length of credit history",
                  "§4": "Hard inquiries", "§5": "Credit mix", "§6": "High-risk products", "§7": "Score impact table"}


def parse(path):
    return parse_front_matter(path.read_text(encoding="utf-8"))


def main() -> int:
    docs, errors = [], []
    for path in sorted(CORPUS.glob("*.md")):
        if path.name == "README.md":
            continue
        meta, body = parse(path)
        if meta is None:
            errors.append(f"{path.name}: missing front matter")
            continue
        errors += [f"{path.name}: missing '{k}'" for k in REQUIRED if not meta.get(k)]
        if meta.get("category") not in CATEGORIES:
            errors.append(f"{path.name}: unknown category {meta.get('category')!r}")
        docs.append({"file": path.name, **meta, "body": body, "words": len(body.split())})

    if len({d["id"] for d in docs}) != len(docs):
        errors.append("duplicate document ids")

    coverage = {}
    for q, facts in KEY_FACTS.items():
        tagged = [d for d in docs if q in d.get("queries", [])]
        text = " ".join(d["body"].lower() for d in tagged)
        missing = [f for f in facts if f.lower() not in text]
        coverage[q] = (tagged, missing)
        if not tagged:
            errors.append(f"sample query {q}: no document tagged")
        if missing:
            errors.append(f"sample query {q}: key facts not found: {missing}")

    sources = " ".join(d["source"] for d in docs)
    guide_missing = [s for s in GUIDE_SECTIONS if s not in sources]
    if guide_missing:
        errors.append(f"guide sections not represented: {guide_missing}")

    lines = ["# Task 7 Evidence: RAG Corpus Summary\n",
             "*Generated by `uv run python scripts/task07_corpus_report.py`. Corpus: `corpus/*.md`.*\n",
             f"**{len(docs)} documents · {sum(d['words'] for d in docs):,} words**\n",
             "| Category | Documents |", "|---|---|"]
    for cat, label in CATEGORIES.items():
        lines.append(f"| {label} (`{cat}`) | {sum(d['category'] == cat for d in docs)} |")
    lines += ["", "## Documents", "", "| # | Title | Category | Words | Sample queries | Source |", "|---|---|---|---|---|---|"]
    for d in docs:
        lines.append(f"| {d['file'][:2]} | {d['title']} | {d['category']} | {d['words']} | "
                     f"{', '.join(map(str, d['queries']))} | {d['source']} |")
    lines += ["", "## Coverage of the 6 sample queries (requirements.md §3)", "",
              "| # | Sample query | Documents | Key facts checked | Result |", "|---|---|---|---|---|"]
    for q, query in SAMPLE_QUERIES.items():
        tagged, missing = coverage[q]
        facts = ", ".join(f'"{f}"' for f in KEY_FACTS[q])
        lines.append(f"| {q} | {query} | {len(tagged)} ({', '.join(d['file'][:2] for d in tagged)}) | {facts} | "
                     f"{'✅ covered' if tagged and not missing else '❌ ' + ', '.join(missing)} |")
    lines += ["", "## Coverage of credit_score_factors_guide.pdf", "",
              "| Section | Topic | Represented in |", "|---|---|---|"]
    for s, topic in GUIDE_SECTIONS.items():
        where = ", ".join(d["file"][:2] for d in docs if s in d["source"])
        lines.append(f"| {s} | {topic} | {where or '❌ none'} |")
    lines += ["", f"**Validation:** {'all checks passed' if not errors else 'FAILED: ' + '; '.join(errors)}."]

    EVIDENCE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
